services:
  db:
    build: db
    restart: always
    # image manual says to set shared memory limit
    shm_size: 128mb
    # expose port for direct connections
    ports:
      - 5432:5432
    networks:
      - backnet
    command: >
      -c ssl=on
      -c ssl_cert_file=/run/secrets/sslcert
      -c ssl_key_file=/run/secrets/sslkey
    environment:
      - POSTGRES_DB=adventureworks
      - POSTGRES_PASSWORD=/run/secrets/dbroot
      - READONLY_PWD_FILE=/run/secrets/readonly
    secrets:
      - dbroot
      - readonly
      - sslcert
      - sslkey
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: backend
    restart: always
    depends_on:
      - db
    networks:
      - backnet
      - frontnet
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@foo.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin
    secrets:
      - pgadmin
    deploy:
      replicas: 3
      resources:
         limits:
            # appropriate for a 2GB RPi
            cpus: '0.5'
            memory: 400m

  proxy:
    build: proxy
    restart: always
    ports:
    - 80:80
    - 443:443
    depends_on:
    - backend
    networks:
    - frontnet
    secrets:
    - sslcert
    - sslkey
    volumes:
    - certbot-www:/var/www/certbot/:ro

networks:
  backnet:
  frontnet:

secrets:
  dbroot:
    environment: "DBROOT"
  readonly:
    environment: "DBUSER"
  pgadmin:
    environment: "PGADMIN"
  sslcert:
    file: /etc/letsencrypt/live/postgres.crwpitcher.com/cert.pem
  sslkey:
    file: /etc/letsencrypt/live/postgres.crwpitcher.com/privkey.pem

volumes:
  pgdata:
  certbot-www:
    external: true
